id: http://w3id.org/mixs/built_environment
name: built_environment
imports:
- linkml:types
- terms
prefixes:
  linkml: https://w3id.org/linkml/
  mixs.vocab: https://w3id.org/mixs/vocab/
  MIXS: https://w3id.org/mixs/terms/
default_prefix: mixs.vocab
slots: {}
classes:
  built environment:
    description: built environment
    mappings: []
    slots:
    - lat_lon
    - depth
    - alt
    - elev
    - geo_loc_name
    - collection_date
    - env_broad_scale
    - env_local_scale
    - env_medium
    - surf_material
    - surf_air_cont
    - rel_air_humidity
    - abs_air_humidity
    - surf_humidity
    - air_temp
    - surf_temp
    - surf_moisture_ph
    - build_occup_type
    - surf_moisture
    - dew_point
    - carb_dioxide
    - ventilation_type
    - organism_count
    - indoor_space
    - indoor_surf
    - filter_type
    - heat_cool_type
    - substructure_type
    - building_setting
    - light_type
    - samp_sort_meth
    - space_typ_state
    - typ_occup_density
    - occup_samp
    - occup_density_samp
    - address
    - adj_room
    - aero_struc
    - amount_light
    - arch_struc
    - avg_occup
    - avg_dew_point
    - avg_temp
    - bathroom_count
    - bedroom_count
    - built_struc_age
    - built_struc_set
    - built_struc_type
    - ceil_area
    - ceil_cond
    - ceil_finish_mat
    - ceil_water_mold
    - ceil_struc
    - ceil_texture
    - ceil_thermal_mass
    - ceil_type
    - cool_syst_id
    - date_last_rain
    - build_docs
    - door_size
    - door_cond
    - door_direct
    - door_loc
    - door_mat
    - door_move
    - door_water_mold
    - door_type
    - door_comp_type
    - door_type_metal
    - door_type_wood
    - drawings
    - elevator
    - escalator
    - exp_duct
    - exp_pipe
    - ext_door
    - fireplace_type
    - floor_age
    - floor_area
    - floor_cond
    - floor_count
    - floor_finish_mat
    - floor_water_mold
    - floor_struc
    - floor_thermal_mass
    - freq_clean
    - freq_cook
    - furniture
    - gender_restroom
    - hall_count
    - handidness
    - heat_deliv_loc
    - heat_system_deliv_meth
    - heat_system_id
    - height_carper_fiber
    - inside_lux
    - int_wall_cond
    - last_clean
    - max_occup
    - mech_struc
    - number_plants
    - number_pets
    - number_resident
    - occup_document
    - ext_wall_orient
    - ext_window_orient
    - rel_humidity_out
    - pres_animal
    - quad_pos
    - rel_samp_loc
    - room_air_exch_rate
    - room_architec_element
    - room_condt
    - room_count
    - room_dim
    - room_door_dist
    - room_loc
    - room_moist_damage_hist
    - room_net_area
    - room_occup
    - room_samp_pos
    - room_type
    - room_vol
    - room_window_count
    - room_connected
    - room_hallway
    - room_door_share
    - room_wall_share
    - samp_weather
    - samp_floor
    - samp_room_id
    - samp_time_out
    - season
    - season_use
    - shading_device_cond
    - shading_device_loc
    - shading_device_mat
    - shading_device_water_mold
    - shading_device_type
    - specific_humidity
    - specific
    - temp_out
    - train_line
    - train_stat_loc
    - train_stop_loc
    - vis_media
    - wall_area
    - wall_const_type
    - wall_finish_mat
    - wall_height
    - wall_loc
    - wall_water_mold
    - wall_surf_treatment
    - wall_texture
    - wall_thermal_mass
    - water_feat_size
    - water_feat_type
    - weekday
    - window_size
    - window_cond
    - window_cover
    - window_horiz_pos
    - window_loc
    - window_mat
    - window_open_freq
    - window_water_mold
    - window_status
    - window_type
    - window_vert_pos
    slot_usage: {}
subsets: {}
enums: {}
